name: Completed Phase 3 Production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: https://grocerylist-notetaking.netlify.app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mark Deployment
        run: |
          echo "Every item is now added as per the basket and history section is also updated."